import { Product } from './types'

export const PRODUCTS: Product[] = [
  // Clothing
  {
    id: '1',
    name: 'Elegant Silk Blouse',
    category: 'Clothing',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1595777712802-5b1d7e2a0b0b?w=500&h=600&fit=crop',
    colors: ['White', 'Beige', 'Rose Gold'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Premium silk blouse with elegant draping and delicate details',
    available: true,
  },
  {
    id: '2',
    name: 'Tailored Evening Dress',
    category: 'Clothing',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=600&fit=crop',
    colors: ['Black', 'Burgundy', 'Champagne'],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Sophisticated evening dress perfect for special occasions',
    available: true,
  },
  {
    id: '3',
    name: 'Cashmere Cardigan',
    category: 'Clothing',
    price: 19999,
    image: 'https://images.unsplash.com/photo-1551522435-a13afa10f103?w=500&h=600&fit=crop',
    colors: ['Cream', 'Taupe', 'Charcoal'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Luxurious cashmere cardigan for everyday elegance',
    available: true,
  },
  {
    id: '4',
    name: 'Premium Denim Jacket',
    category: 'Clothing',
    price: 15999,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=600&fit=crop',
    colors: ['Indigo', 'White', 'Black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Classic denim jacket with premium craftsmanship',
    available: true,
  },
  {
    id: '5',
    name: 'Silk Midi Skirt',
    category: 'Clothing',
    price: 11999,
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&h=600&fit=crop',
    colors: ['Emerald', 'Navy', 'Blush'],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Flowing silk midi skirt with sophisticated drape',
    available: true,
  },
  {
    id: '6',
    name: 'White Linen Shirt',
    category: 'Clothing',
    price: 9999,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=600&fit=crop',
    colors: ['White', 'Cream', 'Light Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Crisp white linen shirt for timeless style',
    available: true,
  },
  
  // Slippers
  {
    id: '7',
    name: 'Luxury Comfort Slippers',
    category: 'Slippers',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1572821833382-d1c04f3e4e56?w=500&h=600&fit=crop',
    colors: ['Beige', 'Rose Gold', 'Gray'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    description: 'Premium comfort slippers with memory foam and plush lining',
    available: true,
  },
  {
    id: '8',
    name: 'Silk-lined House Slippers',
    category: 'Slippers',
    price: 3999,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=600&fit=crop',
    colors: ['Ivory', 'Champagne', 'Taupe'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    description: 'Elegant slippers with genuine silk lining for ultimate comfort',
    available: true,
  },
  {
    id: '9',
    name: 'Fuzzy Slipper Boots',
    category: 'Slippers',
    price: 5999,
    image: 'https://images.unsplash.com/photo-1528148343865-db218b2000cb?w=500&h=600&fit=crop',
    colors: ['White', 'Cream', 'Blush'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    description: 'Cozy slipper boots with premium faux fur exterior',
    available: true,
  },
  {
    id: '10',
    name: 'Heated Massage Slippers',
    category: 'Slippers',
    price: 7999,
    image: 'https://images.unsplash.com/photo-1572821833382-d1c04f3e4e56?w=500&h=600&fit=crop',
    colors: ['Gray', 'Brown', 'Black'],
    sizes: ['5', '6', '7', '8', '9', '10'],
    description: 'Premium slippers with heating and massage functions',
    available: true,
  },
  
  // Jewellery
  {
    id: '11',
    name: 'Gold Pendant Necklace',
    category: 'Jewellery',
    price: 8999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=600&fit=crop',
    colors: ['Gold', 'Rose Gold', 'Silver'],
    sizes: ['One Size'],
    description: 'Elegant 18K gold pendant with diamond accents',
    available: true,
  },
  {
    id: '12',
    name: 'Pearl Earrings Set',
    category: 'Jewellery',
    price: 6999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=600&fit=crop',
    colors: ['White', 'Black', 'Gold'],
    sizes: ['One Size'],
    description: 'Classic pearl earrings with premium pearl quality',
    available: true,
  },
  {
    id: '13',
    name: 'Diamond Tennis Bracelet',
    category: 'Jewellery',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=600&fit=crop',
    colors: ['Gold', 'Silver', 'Rose Gold'],
    sizes: ['One Size'],
    description: 'Stunning tennis bracelet with VS1 diamonds',
    available: true,
  },
  {
    id: '14',
    name: 'Sapphire Ring',
    category: 'Jewellery',
    price: 19999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=600&fit=crop',
    colors: ['Gold', 'Silver'],
    sizes: ['5', '6', '7', '8', '9'],
    description: 'Exquisite sapphire ring with intricate gold setting',
    available: true,
  },
  {
    id: '15',
    name: 'Emerald Brooch',
    category: 'Jewellery',
    price: 14999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=600&fit=crop',
    colors: ['Gold', 'Silver'],
    sizes: ['One Size'],
    description: 'Vintage-style emerald brooch with pearl details',
    available: true,
  },
  {
    id: '16',
    name: 'Gold Chain Bracelet',
    category: 'Jewellery',
    price: 7999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=600&fit=crop',
    colors: ['Gold', 'Rose Gold', 'Silver'],
    sizes: ['One Size'],
    description: 'Delicate 18K gold chain bracelet',
    available: true,
  },
  
  // Customisation
  {
    id: '17',
    name: 'Custom Embroidered Jacket',
    category: 'Customisation',
    price: 22999,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=600&fit=crop',
    colors: ['Black', 'Navy', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Personalized jacket with custom embroidery design',
    available: true,
  },
  {
    id: '18',
    name: 'Monogrammed Leather Bag',
    category: 'Customisation',
    price: 18999,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=600&fit=crop',
    colors: ['Black', 'Cognac', 'Caramel'],
    sizes: ['One Size'],
    description: 'Premium leather bag with personalized monogram',
    available: true,
  },
  {
    id: '19',
    name: 'Custom Printed Scarf',
    category: 'Customisation',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1566564692211-fcb8f41f14f3?w=500&h=600&fit=crop',
    colors: ['Cream', 'Black', 'Navy'],
    sizes: ['One Size'],
    description: 'Silk scarf with custom printed design of your choice',
    available: true,
  },
  {
    id: '20',
    name: 'Personalized Evening Clutch',
    category: 'Customisation',
    price: 13999,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=600&fit=crop',
    colors: ['Gold', 'Silver', 'Rose Gold'],
    sizes: ['One Size'],
    description: 'Custom designed evening clutch with name engraving',
    available: true,
  },
]
